### ISSUE TITLE
Мобильное приложение не коректно работает

### ISSUE THREAD

**Issue by Azamat00** [inaiburger/INAIBurger#4]
При переходе на раздел Карты(Maps) приложение мерцает и дальше не работает @turan21

**Comment by turan21** [comment]
НЕ РАБОТАЕТ ПОТОМУ ЧТО ТЫ ОТКРЫЛ ПРИЛОЖЕНИЕ ЧЕРЕЗ ЭМУЛЯТОР ГДЕ НЕТ ### PLAY MARKET
